#!/usr/bin/env node
/**
 * Reads ../src/data/* at build time and emits worker/src/embedded.ts
 * with all knowledge as inlined string constants.
 *
 * Run via `npm run build` before `wrangler deploy`. The output file is
 * gitignored — every build regenerates it from the canonical sources.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SRC_DATA = resolve(ROOT, "..", "src", "data");
const OUT = join(ROOT, "src", "embedded.ts");

function slurp(file) {
  return readFileSync(join(SRC_DATA, file), "utf-8");
}

const playbooks = {};
for (const file of readdirSync(join(SRC_DATA, "playbooks"))) {
  if (!file.endsWith("-playbook.md")) continue;
  const slug = file.replace(/-playbook\.md$/, "");
  playbooks[slug] = readFileSync(join(SRC_DATA, "playbooks", file), "utf-8");
}

const banner = `// AUTO-GENERATED by scripts/embed-data.mjs. DO NOT EDIT.
// Regenerate with: npm run embed-data (or any build script that runs it).
// Sources: ../src/data/{dataset.json,anti-patterns.md,crosswalks.json,playbooks/*.md}

`;

const out =
  banner +
  `export const DATASET_JSON = ${JSON.stringify(slurp("dataset.json"))};\n\n` +
  `export const ANTI_PATTERNS_MD = ${JSON.stringify(slurp("anti-patterns.md"))};\n\n` +
  `export const CROSSWALKS_JSON = ${JSON.stringify(slurp("crosswalks.json"))};\n\n` +
  `export const PLAYBOOKS: Record<string, string> = ${JSON.stringify(playbooks, null, 2)};\n`;

mkdirSync(join(ROOT, "src"), { recursive: true });
writeFileSync(OUT, out, "utf-8");

const bytes = Buffer.byteLength(out, "utf-8");
console.log(
  `[embed-data] wrote ${OUT} — dataset + crosswalks + anti-patterns + ${Object.keys(playbooks).length} playbooks · ${(bytes / 1024).toFixed(1)} KB`
);
